{
  "hash": "fea47b74cc00a2ec2d2279a40b4cdfd7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Spain contribution to European GDP growth\"\ndate: \"2025-03-15\"\ncategories: [GDP, Eurostat]\nexecute:\n  warning: false\n  message: false\n---\n\n\nA journalist recently asked us if an statement from a politician was true. The statement was that Spain represented half of the European growth. In this (first) post we would learn how to do it using Eurostat data.\n\n## Annual data\n\nFirst, I will show the more direct way to do it for annual data. If we want to calculate it for 2024 we need to get the data for Spain and the EU (or Euro area) for 2023 in current prices and for 2024 in previous year prices (prices of 2023). By difference we can calculate the volume change in both areas.\n\nFirst we load the libraries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(eurostat)\nlibrary(dplyr)\nlibrary(tidyr)\n```\n:::\n\n\nAnd we prepare a query for the data we need. First, the year 2023 in current prices:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_23 <- get_eurostat(\"nama_10_gdp\", \n                    filters = list(geo = c(\"ES\", \"EA20\", \"EU27_2020\"),\n                                   na_item = \"B1GQ\",\n                                   unit = c(\"CP_MEUR\"),\n                                   time_period = 2023),\n                    time_format = \"num\") |> \n  select(geo, time, values)\n```\n:::\n\n\nAnd after the 2024 in previous year prices\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_24 <- get_eurostat(\"nama_10_gdp\", \n                    filters = list(geo = c(\"ES\", \"EA20\", \"EU27_2020\"),\n                                   na_item = \"B1GQ\",\n                                   unit = c(\"PYP_MEUR\"),\n                                   time_period = 2024),\n                    time_format = \"num\") |> \n  select(geo, time, values)\n```\n:::\n\n\nWe bind them together and calculate the change between 2024 and 2023:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- bind_rows(dat_23, dat_24) |> \n  pivot_wider(names_from = time,\n              values_from = values) |> \n  mutate(change = `2024` - `2023`,\n         change_p = round(change / `2023` * 100, 2))  \n\nknitr::kable(dat)\n```\n\n::: {.cell-output-display}\n\n\n|geo       |     2023|     2024|   change| change_p|\n|:---------|--------:|--------:|--------:|--------:|\n|EU27_2020 | 17197822| 17372727| 174905.4|     1.02|\n|EA20      | 14598181| 14722950| 124768.8|     0.85|\n|ES        |  1498324|  1546966|  48642.0|     3.25|\n\n\n:::\n:::\n\n\nSpain grew by 3.25 in 2024 and the EU  by 1.02. But as we are looking for the contribution, we need to divide the change in Spain with the change in the EU.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncont_es_24_eu <- round(dat |> filter(geo == \"ES\") |> select(change) |> pull() / \n                       dat |> filter(geo == \"EU27_2020\") |> select(change) |> pull()\n                       * 100, 2)\n\ncont_es_24_ea <- round(dat |> filter(geo == \"ES\") |> select(change) |> pull() / \n                       dat |> filter(geo == \"EA20\") |> select(change) |> pull()\n                       * 100, 2)\n```\n:::\n\n\n\nFor the EU the contribution was 27.81 and for the Euro area 38.99.\n\n## Quarterly data\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}