project:
  type: website
  output-dir: "docs"

website:
#  title: "blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/luisbia
format:
  html:
    theme: journal
    css: styles.css

editor: visual

