project:
  type: website
  output-dir: "docs"

website:
  title: "blog"
  navbar:
    left:
      - text: Home
        file: index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/luisbia
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

